build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --sub-project-dir=src/php7/
          - phpcs-run
    coverage:
      tests:
        override:
          - command: ./run-test-php
            coverage:
              file: repost/clover.xml
              format: clover
checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: true
        one_class_per_file: false
        side_effects_or_types: true
        no_mixed_inline_html: true
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: true
        avoid_usage_of_logical_operators: true
        psr2_class_declaration: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        blank_line_after_namespace_declaration: true
        single_namespace_per_use: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        avoid_superglobals: true
        security_vulnerabilities: true
        no_exit: true
