build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --sub-project-dir=src/php7/
          - phpcs-run
    coverage:
      tests:
        override:
          - command: ./run-test-php
            coverage:
              file: report/clover.xml
              format: clover
